### ISSUE TITLE
fresh install won't `yarn start`

### ISSUE THREAD

**Issue by mitoskalandiel** [tapnisu/ytscc#47]
node v18.6.0
npm v8.14.0
yarn 1.22 (both via `npm install --global yarn` and `corepack enable`)

all steps up to `yarn build` run fine, but `yarn start` yields the following error output.

this is the collected output from `yarn start` (collected via pipe-redirection, hence the Error/Info prefixes per line)
```
yarn run v1.22.19
$ node .
/home/user/workspace/apps/my_ytscc/dist/Terminal/Input.js:4
const inquirer_1 = require("inquirer");
                   ^

Error [ERR_REQUIRE_ESM]: require() of ES Module /home/user/workspace/apps/my_ytscc/node_modules/inquirer/lib/inquirer.js from /home/user/workspace/ap.
Instead change the require of inquirer.js in /home/user/workspace/apps/my_ytscc/dist/Terminal/Input.js to a dynamic import() which is available in al.
    at Object.<anonymous> (/home/user/workspace/apps/my_ytscc/dist/Terminal/Input.js:4:20)
    at Object.<anonymous> (/home/user/workspace/apps/my_ytscc/dist/Terminal/index.js:17:14)
    at Object.<anonymous> (/home/user/workspace/apps/my_ytscc/dist/Core/index.js:4:17)
    at Object.<anonymous> (/home/user/workspace/apps/my_ytscc/dist/index.js:6:32) {
  code: 'ERR_REQUIRE_ESM'
}

Node.js v18.6.0
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by tapnisu** [comment]
Hello! I think it should work now.

I forgot to test update of inquirer@9.

So i think running `yarn install`,  `yarn fixDependencies`, `yarn build`, `yarn start` will work again.

**Comment by mitoskalandiel** [comment]
Yes indeed, #47 fixed
thanks very much sir for your kind and fast response
